name: Fetch news sync

on:
  push:
    branches: [master]
  schedule:
    - cron:  '*/120 * * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: Pipenv install
        run: |
          pipenv install
      - name: Fetch
        env:
          news-feed-username: ${{ secrets.username }}
          news-feed-password: ${{ secrets.password }}
        run: |
          pipenv run python news_feed.py sync
